version: '3'
services:
  db:
    image: postgres:12
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  odoo:
    image: odoo:14
    container_name: odoo_app
    restart: always
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "8069:8069"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
      PGDATA: /var/lib/postgresql/data
      ODOO_DB_HOST: db
      ODOO_DB_PORT: 5432
      ODOO_DB_USER: odoo
      ODOO_DB_PASSWORD: odoo
      ODOO_DB_NAME: odoo
    volumes:
      - ./config:/etc/odoo
      - odoo_addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - odoo_log:/var/log/odoo

volumes:
  pg_data:
  odoo_addons:
  odoo_data:
  odoo_log: